apiVersion: v1
kind: Namespace
metadata:
   name: attack-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: attack-ns
  name: attack-deployment
  labels:
    app: attack-deployment
spec:
  replicas: 50
  selector:
    matchLabels:
      app: attack-deployment
  template:
    metadata:
      labels:
        app: attack-deployment
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: attack-deployment
      containers:
      - name: attack-box
        image: alessiofilippin/just-another-boring-crawler-cli
        resources:
          limits:
            memory: "250Mi"
            cpu: "200m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        args: ["BulkCall","https://alef-target-app.azurewebsites.net/", "20", "300", "http://51.137.116.196:3129"]
      tolerations:
      - key: "node.kubernetes.io/memory-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Always