apiVersion: v1
kind: Namespace
metadata:
   name: attack-ns
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: attack-ns
  name: attack-batch-job
  labels:
    app: attack-batch-job
spec:
  parallelism: 10
  completions: 10
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: attack-batch-job   
      containers:
      - name: attack-box
        image: alessiofilippin/just-another-boring-crawler-cli
        resources:
          limits:
            memory: "250Mi"
            cpu: "200m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        args: ["BulkCall","https://alef-target-app.azurewebsites.net/", "20", "300"]
      tolerations:
      - key: "node.kubernetes.io/memory-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 4